# Generated by Django 4.2.30 on 2026-08-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_percentage', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='sales_reporting.category')),
                ('sales_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='sales_reporting.salesimport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoryresult',
            constraint=models.UniqueConstraint(fields=('sales_import', 'category'), name='unique_category_result_per_import'),
        ),
    ]
